version: '3.7'

services:
    api:
        build: .
        image: node:lts-alpine
        depends_on:
            - mssql
            - mysql
        container_name: api-boilerplate
        restart: unless-stopped
        env_file:
            - .env
        environment:
            - DB_MYSQL_HOST=mysql
            - DB_MSSQL_HOST=mssql
        volumes:
            - .:/app/
        working_dir: /app
        links: 
            - mssql
            - mysql
        # networks:
        #     - app-network
        ports:
            - '$PORT:3000'
            - '7001:7001'
        command: npm run dev:docker

    mssql:
        build:
            context: ./development-db
        container_name: mssql
        restart: always
        environment:
            - DB_MSSQL_DATABASE=$DB_MSSQL_DATABASE
            - DB_MSSQL_PASSWORD=$DB_MSSQL_PASSWORD
            - ACCEPT_EULA=Y
            - SA_PASSWORD=$DB_MSSQL_PASSWORD
        ports:
            - 1433:1433

    mysql:
        image: mysql
        container_name: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_DATABASE: $DB_MYSQL_DATABASE
            MYSQL_ROOT_PASSWORD: $DB_MYSQL_PASSWORD
        ports:
            - 3306:3306
