version: '3.7'

services:
    mysql:
        image: mysql
        container_name: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_DATABASE: DB_SCHEMA
            # Password for root access
            MYSQL_ROOT_PASSWORD: root
        ports:
            # <Port exposed> : < MySQL Port running inside container>
            - 3306:3306

    mssql:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: mssql
        restart: always
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=Password1!
        ports:
            - 1433:1433